### C - Create
POST http://localhost:8080/client
Context-Type: application/json

{
	"id": 1,
	"name": "Andre",
	"birthDate": "1998-02-17",
	"sex": "M",
	"healthIssue": [{
					  "name": "diabetes",
					  "degree": 2}],
	"creationDate": "2021-04-29",
	"updateDate": "2021-04-29"
	
}

### R - Read
GET http://localhost:8080/client
Context-Type: application/json

### U - Update
PUT http://localhost:8080/client
Context-Type: application/json

{
	"id": 1,
	"name": "Andre Germano",
	"birthDate": "1998-02-18",
	"sex": "M",
	"healthIssue": [{
					  "name": "diabetes",
					  "degree": 1}],
	"creationDate": "2021-04-29",
	"updateDate": "2021-04-30"
	
}

### D - Delete
DELETE http://localhost:8080/cliente/1


